import Foundation

// MARK: - All Positions Data
struct PositionData {
    static let allPositions: [Position] = [
        Position(
            id: "missionary", name: "Misionarul", nameEn: "Missionary",
            category: .romantic, difficulty: .beginner, intimacy: 5,
            image: "missionary",
            description: "Pozitia clasica si intima, perfecta pentru conexiune emotionala profunda.",
            descriptionEn: "The classic and intimate position, perfect for deep emotional connection.",
            benefits: ["Contact vizual intim", "Permite sarutari", "Usor de practicat", "Stimulare prin contact direct"],
            benefitsEn: ["Intimate eye contact", "Allows kissing", "Easy to practice", "Stimulation through direct contact"],
            tips: ["Folositi perne sub solduri", "Mentineti contactul vizual", "Experimentati cu ritmuri diferite"],
            tipsEn: ["Use pillows under hips", "Maintain eye contact", "Experiment with different rhythms"],
            variations: ["Cu picioarele ridicate", "Cu perna sub solduri", "Cu picioarele incrucisate"],
            variationsEn: ["With legs raised", "With pillow under hips", "With legs crossed"]
        ),
        Position(
            id: "cowgirl", name: "Cowgirl", nameEn: "Cowgirl",
            category: .passionate, difficulty: .beginner, intimacy: 4,
            image: "cowgirl",
            description: "Partenera preia controlul complet in aceasta pozitie dominanta si senzuala.",
            descriptionEn: "The partner takes full control in this dominant and sensual position.",
            benefits: ["Control complet pentru partenera", "Stimulare clitoridiana", "Varietate de unghiuri", "Vedere completa"],
            benefitsEn: ["Full control for partner", "Clitoral stimulation", "Variety of angles", "Full view"],
            tips: ["Experimentati cu miscari circulare", "Sprijiniti-va pe piept", "Variati viteza"],
            tipsEn: ["Experiment with circular movements", "Lean on chest", "Vary the speed"],
            variations: ["Reverse cowgirl", "Aplecare inainte", "Cu genunchii uniti"],
            variationsEn: ["Reverse cowgirl", "Leaning forward", "With knees together"]
        ),
        Position(
            id: "doggy-style", name: "Doggy Style", nameEn: "Doggy Style",
            category: .passionate, difficulty: .beginner, intimacy: 3,
            image: "doggy-style",
            description: "O pozitie intensa care permite penetrare profunda si stimulare intensa.",
            descriptionEn: "An intense position that allows deep penetration and intense stimulation.",
            benefits: ["Penetrare profunda", "Stimulare punct G", "Acces liber la corp", "Intensitate ridicata"],
            benefitsEn: ["Deep penetration", "G-spot stimulation", "Free access to body", "High intensity"],
            tips: ["Ajustati unghiul soldurilor", "Folositi perne pentru confort", "Comunicati ritmul preferat"],
            tipsEn: ["Adjust hip angle", "Use pillows for comfort", "Communicate preferred rhythm"],
            variations: ["Cu fata in jos", "In picioare", "Peste marginea patului"],
            variationsEn: ["Face down", "Standing", "Over the edge of the bed"]
        ),
        Position(
            id: "spooning", name: "Lingurita", nameEn: "Spooning",
            category: .romantic, difficulty: .beginner, intimacy: 5,
            image: "spooning",
            description: "Pozitie intima si relaxanta, perfecta pentru momente de tandrete.",
            descriptionEn: "Intimate and relaxing position, perfect for tender moments.",
            benefits: ["Foarte intim", "Relaxant", "Perfect pentru dimineata", "Acces la intreg corpul"],
            benefitsEn: ["Very intimate", "Relaxing", "Perfect for morning", "Access to entire body"],
            tips: ["Folositi perne pentru aliniere", "Ridicati usor piciorul", "Explorati cu mainile"],
            tipsEn: ["Use pillows for alignment", "Slightly raise the leg", "Explore with hands"],
            variations: ["Cu piciorul ridicat", "Fata in fata", "Cu perna intre picioare"],
            variationsEn: ["With raised leg", "Face to face", "With pillow between legs"]
        ),
        Position(
            id: "lotus", name: "Lotus", nameEn: "Lotus",
            category: .intimate, difficulty: .intermediate, intimacy: 5,
            image: "lotus",
            description: "Pozitie tantra profund intima cu contact corporal total.",
            descriptionEn: "Deeply intimate tantra position with total body contact.",
            benefits: ["Conexiune emotionala maxima", "Contact total", "Ritm lent si profund", "Respiratie sincronizata"],
            benefitsEn: ["Maximum emotional connection", "Total contact", "Slow and deep rhythm", "Synchronized breathing"],
            tips: ["Practicati respiratia sincronizata", "Mentineti contactul vizual", "Nu va grabiti"],
            tipsEn: ["Practice synchronized breathing", "Maintain eye contact", "Don't rush"],
            variations: ["Cu picioarele intinse", "Cu sprijin pe spate", "Cu legatura bratelor"],
            variationsEn: ["With extended legs", "With back support", "With arm embrace"]
        ),
        Position(
            id: "reverse-cowgirl", name: "Cowgirl Inversa", nameEn: "Reverse Cowgirl",
            category: .adventurous, difficulty: .intermediate, intimacy: 3,
            image: "reverse-cowgirl",
            description: "Varianta inversa a cowgirl-ului cu un unghi complet diferit de stimulare.",
            descriptionEn: "The reverse variant of cowgirl with a completely different stimulation angle.",
            benefits: ["Unghi nou de stimulare", "Control pentru partenera", "Vedere diferita", "Stimulare intensa"],
            benefitsEn: ["New stimulation angle", "Control for partner", "Different view", "Intense stimulation"],
            tips: ["Sprijiniti-va pe genunchi", "Experimentati cu unghiuri", "Comunicati ce simtiti"],
            tipsEn: ["Support yourself on knees", "Experiment with angles", "Communicate what you feel"],
            variations: ["Aplecare inainte", "Cu picioarele intinse", "Sprijin pe maini"],
            variationsEn: ["Leaning forward", "With extended legs", "Hand support"]
        ),
        Position(
            id: "standing", name: "In Picioare", nameEn: "Standing",
            category: .adventurous, difficulty: .advanced, intimacy: 3,
            image: "standing",
            description: "Pozitie dinamica si spontana, perfecta pentru momente de pasiune intensa.",
            descriptionEn: "Dynamic and spontaneous position, perfect for moments of intense passion.",
            benefits: ["Foarte spontan", "Intensitate ridicata", "Adrenalina", "Nu necesita pat"],
            benefitsEn: ["Very spontaneous", "High intensity", "Adrenaline", "No bed needed"],
            tips: ["Gasiti un perete stabil", "Diferenta de inaltime conteaza", "Tineti-va bine"],
            tipsEn: ["Find a stable wall", "Height difference matters", "Hold on tight"],
            variations: ["Langa perete", "Fata in fata", "Din spate"],
            variationsEn: ["Against wall", "Face to face", "From behind"]
        ),
        Position(
            id: "69", name: "69", nameEn: "69",
            category: .passionate, difficulty: .intermediate, intimacy: 4,
            image: "69",
            description: "Placere reciproca simultana intr-o pozitie clasica de intimitate orala.",
            descriptionEn: "Simultaneous mutual pleasure in a classic oral intimacy position.",
            benefits: ["Placere reciproca", "Intimitate crescuta", "Stimulare simultana", "Varietate"],
            benefitsEn: ["Mutual pleasure", "Increased intimacy", "Simultaneous stimulation", "Variety"],
            tips: ["Gasiti o pozitie confortabila", "Comunicati preferintele", "Alternati ritmul"],
            tipsEn: ["Find a comfortable position", "Communicate preferences", "Alternate rhythm"],
            variations: ["Pe lateral", "Cu partenera deasupra", "Cu perna sub cap"],
            variationsEn: ["On the side", "With partner on top", "With pillow under head"]
        ),
        Position(
            id: "scissors", name: "Foarfeca", nameEn: "Scissors",
            category: .intimate, difficulty: .intermediate, intimacy: 4,
            image: "scissors",
            description: "Pozitie unica cu picioarele impletite pentru o conexiune diferita.",
            descriptionEn: "Unique position with intertwined legs for a different connection.",
            benefits: ["Unghi unic", "Stimulare clitoridiana", "Relaxant", "Contact vizual"],
            benefitsEn: ["Unique angle", "Clitoral stimulation", "Relaxing", "Eye contact"],
            tips: ["Ajustati unghiul picioarelor", "Miscari lente", "Folositi lubrifiant"],
            tipsEn: ["Adjust leg angle", "Slow movements", "Use lubricant"],
            variations: ["Cu picioarele ridicate", "Pe lateral", "Cu perna sub solduri"],
            variationsEn: ["With raised legs", "On the side", "With pillow under hips"]
        ),
        Position(
            id: "pretzel", name: "Pretzel", nameEn: "Pretzel",
            category: .adventurous, difficulty: .advanced, intimacy: 4,
            image: "pretzel",
            description: "Pozitie creativa cu impletirea corpurilor pentru senzatii noi.",
            descriptionEn: "Creative position with intertwined bodies for new sensations.",
            benefits: ["Senzatii noi", "Penetrare profunda", "Contact corporal", "Intimitate"],
            benefitsEn: ["New sensations", "Deep penetration", "Body contact", "Intimacy"],
            tips: ["Flexibilitate necesara", "Incalziti-va inainte", "Comunicati confortul"],
            tipsEn: ["Flexibility required", "Warm up before", "Communicate comfort level"],
            variations: ["Cu torsiunea mai mica", "Cu perna de sprijin", "Varianta relaxata"],
            variationsEn: ["With less twist", "With support pillow", "Relaxed variant"]
        ),
        Position(
            id: "bridge", name: "Podul", nameEn: "The Bridge",
            category: .adventurous, difficulty: .expert, intimacy: 3,
            image: "bridge",
            description: "Pozitie acrobatica cu partenerul in pozitia podului pentru stimulare intensa.",
            descriptionEn: "Acrobatic position with partner in bridge position for intense stimulation.",
            benefits: ["Stimulare intensa", "Unghi profund", "Impresionant vizual", "Provocare fizica"],
            benefitsEn: ["Intense stimulation", "Deep angle", "Visually impressive", "Physical challenge"],
            tips: ["Necesita forta in brate", "Incalziti-va bine", "Nu fortati"],
            tipsEn: ["Requires arm strength", "Warm up well", "Don't force it"],
            variations: ["Cu sprijin pe coate", "Jumatate de pod", "Cu perna sub spate"],
            variationsEn: ["With elbow support", "Half bridge", "With pillow under back"]
        ),
        Position(
            id: "butterfly", name: "Fluturele", nameEn: "The Butterfly",
            category: .passionate, difficulty: .intermediate, intimacy: 4,
            image: "butterfly",
            description: "Partenera la marginea patului cu picioarele ridicate ca aripile unui fluture.",
            descriptionEn: "Partner at the edge of the bed with legs raised like butterfly wings.",
            benefits: ["Penetrare profunda", "Unghi perfect", "Stimulare G-spot", "Vedere completa"],
            benefitsEn: ["Deep penetration", "Perfect angle", "G-spot stimulation", "Full view"],
            tips: ["Folositi marginea patului", "Ajustati inaltimea", "Tineti picioarele partenerului"],
            tipsEn: ["Use the edge of the bed", "Adjust height", "Hold partner's legs"],
            variations: ["Cu picioarele pe umeri", "Cu picioarele deschise", "Cu perna sub solduri"],
            variationsEn: ["With legs on shoulders", "With legs open", "With pillow under hips"]
        ),
        Position(
            id: "amazon", name: "Amazoana", nameEn: "Amazon",
            category: .adventurous, difficulty: .advanced, intimacy: 4,
            image: "amazon",
            description: "Partenera domina complet in aceasta pozitie puternica si intensa.",
            descriptionEn: "The partner fully dominates in this powerful and intense position.",
            benefits: ["Dominanta feminina", "Control complet", "Stimulare intensa", "Perspectiva noua"],
            benefitsEn: ["Female dominance", "Full control", "Intense stimulation", "New perspective"],
            tips: ["Comunicati limitele", "Incepeti incet", "Folositi perne"],
            tipsEn: ["Communicate limits", "Start slowly", "Use pillows"],
            variations: ["Inversa", "Cu sprijin pe genunchi", "Cu aplecare inainte"],
            variationsEn: ["Reverse", "With knee support", "With forward lean"]
        ),
        Position(
            id: "wheelbarrow", name: "Roaba", nameEn: "Wheelbarrow",
            category: .adventurous, difficulty: .expert, intimacy: 2,
            image: "wheelbarrow",
            description: "Pozitie atletica unde partenerul sustine picioarele partenerei.",
            descriptionEn: "Athletic position where the partner holds their partner's legs.",
            benefits: ["Foarte intens", "Adrenalina", "Unghi profund", "Provocare fizica"],
            benefitsEn: ["Very intense", "Adrenaline", "Deep angle", "Physical challenge"],
            tips: ["Necesita forta", "Suprafata stabila", "Incepeti cu varianta usoara"],
            tipsEn: ["Requires strength", "Stable surface", "Start with the easy variant"],
            variations: ["Cu sprijin pe pat", "In picioare", "Cu sprijin pe perete"],
            variationsEn: ["With bed support", "Standing", "With wall support"]
        ),
        Position(
            id: "lazy-dog", name: "Catelul Lenes", nameEn: "Lazy Dog",
            category: .romantic, difficulty: .beginner, intimacy: 4,
            image: "lazy-dog",
            description: "Varianta relaxata a pozitiei doggy, cu partenera intinsa confortabil.",
            descriptionEn: "Relaxed variant of doggy position, with partner lying comfortably.",
            benefits: ["Foarte confortabil", "Penetrare profunda", "Relaxant", "Perfect pentru dimineata"],
            benefitsEn: ["Very comfortable", "Deep penetration", "Relaxing", "Perfect for morning"],
            tips: ["Folositi perna sub solduri", "Miscari lente", "Explorati cu mainile"],
            tipsEn: ["Use pillow under hips", "Slow movements", "Explore with hands"],
            variations: ["Cu picioarele unite", "Cu picioarele deschise", "Cu perna sub burta"],
            variationsEn: ["With legs together", "With legs apart", "With pillow under belly"]
        ),
        Position(
            id: "seated", name: "Sezut", nameEn: "Seated",
            category: .intimate, difficulty: .intermediate, intimacy: 5,
            image: "seated",
            description: "Fata in fata pe scaun sau pe marginea patului, extrem de intim.",
            descriptionEn: "Face to face on a chair or edge of the bed, extremely intimate.",
            benefits: ["Foarte intim", "Contact total", "Permite sarutari", "Control partajat"],
            benefitsEn: ["Very intimate", "Total contact", "Allows kissing", "Shared control"],
            tips: ["Scaun stabil", "Mentineti contactul vizual", "Miscari de legananare"],
            tipsEn: ["Stable chair", "Maintain eye contact", "Rocking movements"],
            variations: ["Pe scaun", "Pe marginea patului", "Pe podea"],
            variationsEn: ["On chair", "On edge of bed", "On floor"]
        ),
        Position(
            id: "the-chair", name: "Scaunul", nameEn: "The Chair",
            category: .passionate, difficulty: .intermediate, intimacy: 4,
            image: "the-chair",
            description: "Partenerul sta pe scaun cu partenera deasupra pentru control complet.",
            descriptionEn: "Partner sits on chair with other partner on top for full control.",
            benefits: ["Control pentru partenera", "Stimulare profunda", "Spontan", "Versatil"],
            benefitsEn: ["Control for partner", "Deep stimulation", "Spontaneous", "Versatile"],
            tips: ["Scaun fara brate", "Folositi spatarul", "Variati unghiul"],
            tipsEn: ["Chair without arms", "Use the backrest", "Vary the angle"],
            variations: ["Fata in fata", "Cu spatele", "Pe marginea scaunului"],
            variationsEn: ["Face to face", "Facing away", "On edge of chair"]
        ),
        Position(
            id: "waterfall", name: "Cascada", nameEn: "The Waterfall",
            category: .adventurous, difficulty: .advanced, intimacy: 3,
            image: "waterfall",
            description: "Partenerul cu capul in jos de pe marginea patului pentru senzatii intense.",
            descriptionEn: "Partner hanging head down from edge of bed for intense sensations.",
            benefits: ["Senzatii intense", "Flux sanguin crescut", "Unghi unic", "Experienta noua"],
            benefitsEn: ["Intense sensations", "Increased blood flow", "Unique angle", "New experience"],
            tips: ["Nu stati prea mult cu capul in jos", "Aveti grija la siguranta", "Perna pe podea"],
            tipsEn: ["Don't stay upside down too long", "Be careful about safety", "Pillow on floor"],
            variations: ["Doar partial", "Cu sprijin pe maini", "Varianta laterala"],
            variationsEn: ["Only partially", "With hand support", "Side variant"]
        ),
        Position(
            id: "ballet-dancer", name: "Balerina", nameEn: "Ballet Dancer",
            category: .passionate, difficulty: .advanced, intimacy: 4,
            image: "ballet-dancer",
            description: "In picioare cu un picior ridicat, ca o balerina eleganta.",
            descriptionEn: "Standing with one leg raised, like an elegant ballet dancer.",
            benefits: ["Elegant", "Romantic", "Stimulare diferita", "Spontan"],
            benefitsEn: ["Elegant", "Romantic", "Different stimulation", "Spontaneous"],
            tips: ["Flexibilitate necesara", "Sprijiniti-va de perete", "Incalziti-va"],
            tipsEn: ["Flexibility required", "Lean against wall", "Warm up first"],
            variations: ["Cu piciorul pe umar", "Cu sprijin pe perete", "Cu partenerul sustinand piciorul"],
            variationsEn: ["With leg on shoulder", "With wall support", "With partner holding leg"]
        ),
        Position(
            id: "the-snake", name: "Sarpele", nameEn: "The Snake",
            category: .intimate, difficulty: .intermediate, intimacy: 4,
            image: "the-snake",
            description: "Partenera intinsa pe burta cu partenerul deasupra, miscare de unduit.",
            descriptionEn: "Partner lying face down with other partner on top, undulating movement.",
            benefits: ["Stimulare intensa", "Contact corporal total", "Miscare naturala", "Foarte senzual"],
            benefitsEn: ["Intense stimulation", "Total body contact", "Natural movement", "Very sensual"],
            tips: ["Folositi tot corpul", "Miscari de unduit", "Ritmul e important"],
            tipsEn: ["Use entire body", "Undulating movements", "Rhythm is important"],
            variations: ["Cu picioarele unite", "Cu bratele intinse", "Cu perna sub solduri"],
            variationsEn: ["With legs together", "With arms extended", "With pillow under hips"]
        ),
        Position(
            id: "the-cradle", name: "Leaganul", nameEn: "The Cradle",
            category: .romantic, difficulty: .intermediate, intimacy: 5,
            image: "the-cradle",
            description: "Pozitie intima cu partenerul tinand partenera in brate ca intr-un leagan.",
            descriptionEn: "Intimate position with partner holding their partner in arms like a cradle.",
            benefits: ["Extrem de intim", "Protector", "Romantic", "Contact emotional"],
            benefitsEn: ["Extremely intimate", "Protective", "Romantic", "Emotional contact"],
            tips: ["Folositi perne", "Mentineti contactul vizual", "Miscare de legananare"],
            tipsEn: ["Use pillows", "Maintain eye contact", "Rocking movement"],
            variations: ["Cu picioarele incrucisate", "Cu sprijin pe spate", "Varianta laterala"],
            variationsEn: ["With legs crossed", "With back support", "Side variant"]
        ),
        Position(
            id: "the-arc", name: "Arcul", nameEn: "The Arc",
            category: .adventurous, difficulty: .advanced, intimacy: 3,
            image: "the-arc",
            description: "Partenera se arcuieste inapoi pentru un unghi de penetrare unic.",
            descriptionEn: "Partner arches back for a unique penetration angle.",
            benefits: ["Unghi unic", "Stimulare intensa", "Vizual impresionant", "Senzatii noi"],
            benefitsEn: ["Unique angle", "Intense stimulation", "Visually impressive", "New sensations"],
            tips: ["Flexibilitate necesara", "Sprijin pentru spate", "Nu fortati arcuirea"],
            tipsEn: ["Flexibility required", "Back support", "Don't force the arch"],
            variations: ["Cu sprijin pe maini", "Semi-arcuit", "Cu perna sub spate"],
            variationsEn: ["With hand support", "Semi-arched", "With pillow under back"]
        ),
        Position(
            id: "the-eagle", name: "Vulturul", nameEn: "The Eagle",
            category: .passionate, difficulty: .intermediate, intimacy: 3,
            image: "the-eagle",
            description: "Partenera cu picioarele larg deschise ca aripile unui vultur.",
            descriptionEn: "Partner with legs wide open like eagle wings.",
            benefits: ["Acces complet", "Penetrare profunda", "Stimulare intensa", "Unghi perfect"],
            benefitsEn: ["Full access", "Deep penetration", "Intense stimulation", "Perfect angle"],
            tips: ["Perne sub solduri", "Comunicati confortul", "Experimentati cu unghiuri"],
            tipsEn: ["Pillows under hips", "Communicate comfort", "Experiment with angles"],
            variations: ["Cu picioarele pe umeri", "Cu picioarele tinute", "Varianta laterala"],
            variationsEn: ["With legs on shoulders", "With legs held", "Side variant"]
        ),
        Position(
            id: "the-plow", name: "Plugul", nameEn: "The Plow",
            category: .adventurous, difficulty: .expert, intimacy: 3,
            image: "the-plow",
            description: "Partenera cu picioarele ridicate peste cap pentru penetrare foarte profunda.",
            descriptionEn: "Partner with legs raised over head for very deep penetration.",
            benefits: ["Penetrare foarte profunda", "Stimulare G-spot intensa", "Senzatii noi", "Provocare fizica"],
            benefitsEn: ["Very deep penetration", "Intense G-spot stimulation", "New sensations", "Physical challenge"],
            tips: ["Flexibilitate necesara", "Incalziti-va", "Comunicati limita"],
            tipsEn: ["Flexibility required", "Warm up", "Communicate limits"],
            variations: ["Partial", "Cu sprijin pe perete", "Cu perna sub gat"],
            variationsEn: ["Partial", "With wall support", "With pillow under neck"]
        ),
        Position(
            id: "the-dolphin", name: "Delfinul", nameEn: "The Dolphin",
            category: .passionate, difficulty: .intermediate, intimacy: 3,
            image: "the-dolphin",
            description: "Partenera in pozitia delfinului cu soldurile ridicate si capul jos.",
            descriptionEn: "Partner in dolphin position with hips raised and head down.",
            benefits: ["Unghi profund", "Stimulare intensa", "Pozitie dinamica", "Senzatii unice"],
            benefitsEn: ["Deep angle", "Intense stimulation", "Dynamic position", "Unique sensations"],
            tips: ["Folositi perne sub genunchi", "Bratele intinse inainte", "Controlati ritmul"],
            tipsEn: ["Use pillows under knees", "Arms extended forward", "Control the rhythm"],
            variations: ["Cu bratele pe spate", "Cu fata pe perna", "Cu genunchii mai apropiati"],
            variationsEn: ["With arms on back", "With face on pillow", "With knees closer together"]
        ),
        Position(
            id: "the-spider", name: "Paianjenul", nameEn: "The Spider",
            category: .intimate, difficulty: .intermediate, intimacy: 4,
            image: "the-spider",
            description: "Ambii parteneri fata in fata cu picioarele impletite, sprijiniti pe maini.",
            descriptionEn: "Both partners face to face with intertwined legs, supported on hands.",
            benefits: ["Contact vizual", "Ritm sincronizat", "Intimitate crescuta", "Stimulare reciproca"],
            benefitsEn: ["Eye contact", "Synchronized rhythm", "Increased intimacy", "Mutual stimulation"],
            tips: ["Gasiti echilibrul", "Perne pentru confort", "Miscari sincronizate"],
            tipsEn: ["Find balance", "Pillows for comfort", "Synchronized movements"],
            variations: ["Cu un picior ridicat", "Mai apropiati", "Cu sprijin pe coate"],
            variationsEn: ["With one leg raised", "Closer together", "With elbow support"]
        ),
        Position(
            id: "the-pretzel-dip", name: "Pretzel cu Sos", nameEn: "Pretzel Dip",
            category: .intimate, difficulty: .intermediate, intimacy: 4,
            image: "the-pretzel-dip",
            description: "Varianta laterala a pretzel-ului cu penetrare laterala intima.",
            descriptionEn: "Side variant of pretzel with intimate lateral penetration.",
            benefits: ["Foarte intim", "Confortabil", "Acces pentru sarutari", "Stimulare diferita"],
            benefitsEn: ["Very intimate", "Comfortable", "Access for kissing", "Different stimulation"],
            tips: ["Perne intre picioare", "Gasiti unghiul corect", "Miscari lente"],
            tipsEn: ["Pillows between legs", "Find the right angle", "Slow movements"],
            variations: ["Cu piciorul ridicat mai sus", "Cu bratele impletite", "Varianta mai deschisa"],
            variationsEn: ["With leg raised higher", "With arms intertwined", "More open variant"]
        ),
        Position(
            id: "the-anvil", name: "Nicovala", nameEn: "The Anvil",
            category: .passionate, difficulty: .intermediate, intimacy: 3,
            image: "the-anvil",
            description: "Partenera cu picioarele ridicate pe umerii partenerului.",
            descriptionEn: "Partner with legs raised on the other partner's shoulders.",
            benefits: ["Penetrare foarte profunda", "Stimulare intensa", "Dominanta", "Unghi perfect"],
            benefitsEn: ["Very deep penetration", "Intense stimulation", "Dominance", "Perfect angle"],
            tips: ["Incepeti incet", "Comunicati adancimea", "Perne sub solduri"],
            tipsEn: ["Start slowly", "Communicate depth", "Pillows under hips"],
            variations: ["Un picior pe umar", "Ambele picioare sus", "Cu genunchii indoiti"],
            variationsEn: ["One leg on shoulder", "Both legs up", "With bent knees"]
        ),
        Position(
            id: "the-twist", name: "Rasucirea", nameEn: "The Twist",
            category: .adventurous, difficulty: .advanced, intimacy: 3,
            image: "the-twist",
            description: "Pozitie cu rasucirea corpului pentru un unghi complet nou de stimulare.",
            descriptionEn: "Position with body twist for a completely new stimulation angle.",
            benefits: ["Senzatii complet noi", "Stimulare diferita", "Provocare fizica", "Experienta unica"],
            benefitsEn: ["Completely new sensations", "Different stimulation", "Physical challenge", "Unique experience"],
            tips: ["Nu rasuciti prea mult", "Flexibilitate necesara", "Opriti daca simtiti disconfort"],
            tipsEn: ["Don't twist too much", "Flexibility required", "Stop if you feel discomfort"],
            variations: ["Rasucire usoara", "Cu sprijin pe coate", "Varianta pe lateral"],
            variationsEn: ["Light twist", "With elbow support", "Side variant"]
        ),
        Position(
            id: "the-wave", name: "Valul", nameEn: "The Wave",
            category: .romantic, difficulty: .intermediate, intimacy: 4,
            image: "the-wave",
            description: "Miscare ondulatorie a corpurilor sincronizate ca valurile marii.",
            descriptionEn: "Undulating movement of bodies synchronized like ocean waves.",
            benefits: ["Foarte senzual", "Ritm natural", "Conexiune profunda", "Miscare fluida"],
            benefitsEn: ["Very sensual", "Natural rhythm", "Deep connection", "Fluid movement"],
            tips: ["Sincronizati respiratia", "Miscari fluide", "Lasati-va dusi de ritm"],
            tipsEn: ["Synchronize breathing", "Fluid movements", "Let the rhythm guide you"],
            variations: ["Rapid", "Lent", "Cu pauze"],
            variationsEn: ["Fast", "Slow", "With pauses"]
        ),
        Position(
            id: "the-rocking-horse", name: "Calul Balansoar", nameEn: "Rocking Horse",
            category: .intimate, difficulty: .intermediate, intimacy: 5,
            image: "the-rocking-horse",
            description: "Partenera in poala partenerului cu miscare de legananare.",
            descriptionEn: "Partner in lap with rocking movement.",
            benefits: ["Extrem de intim", "Contact total", "Ritm de legananare", "Sarutari usor de oferit"],
            benefitsEn: ["Extremely intimate", "Total contact", "Rocking rhythm", "Easy to kiss"],
            tips: ["Mentineti contactul vizual", "Miscare de legananare", "Imbratisati-va"],
            tipsEn: ["Maintain eye contact", "Rocking movement", "Embrace each other"],
            variations: ["Pe canapea", "Pe podea", "Pe marginea patului"],
            variationsEn: ["On couch", "On floor", "On edge of bed"]
        ),
        Position(
            id: "the-jockey", name: "Jocheul", nameEn: "The Jockey",
            category: .passionate, difficulty: .intermediate, intimacy: 3,
            image: "the-jockey",
            description: "Partenera intinsa pe burta cu partenerul calare, control complet.",
            descriptionEn: "Partner lying face down with other partner on top, full control.",
            benefits: ["Penetrare profunda", "Control pentru partener", "Stimulare intensa", "Contact corporal"],
            benefitsEn: ["Deep penetration", "Control for partner", "Intense stimulation", "Body contact"],
            tips: ["Nu puneti prea multa greutate", "Miscari de solduri", "Comunicati presiunea"],
            tipsEn: ["Don't put too much weight", "Hip movements", "Communicate pressure"],
            variations: ["Cu bratele partenerei intinse", "Cu perna sub solduri", "Cu genunchii pe laterale"],
            variationsEn: ["With partner's arms extended", "With pillow under hips", "With knees on sides"]
        ),
        Position(
            id: "the-deck-chair", name: "Sezlongul", nameEn: "The Deck Chair",
            category: .adventurous, difficulty: .advanced, intimacy: 3,
            image: "the-deck-chair",
            description: "Partenerul pe spate semi-ridicat cu partenera deasupra in unghi.",
            descriptionEn: "Partner semi-reclined on back with other partner on top at an angle.",
            benefits: ["Unghi diferit", "Vedere completa", "Stimulare profunda", "Control partajat"],
            benefitsEn: ["Different angle", "Full view", "Deep stimulation", "Shared control"],
            tips: ["Folositi perne pentru unghi", "Gasiti echilibrul", "Experimentati pozitia"],
            tipsEn: ["Use pillows for angle", "Find balance", "Experiment with position"],
            variations: ["Mai ridicat", "Mai aplecat", "Cu picioarele intinse"],
            variationsEn: ["More reclined", "More angled", "With extended legs"]
        ),
        Position(
            id: "the-catherine-wheel", name: "Roata Catherinei", nameEn: "Catherine Wheel",
            category: .adventurous, difficulty: .expert, intimacy: 4,
            image: "the-catherine-wheel",
            description: "Pozitie circulara complexa cu ambii parteneri sprijiniti pe maini si picioare.",
            descriptionEn: "Complex circular position with both partners supported on hands and feet.",
            benefits: ["Foarte unic", "Provocare fizica", "Senzatii noi", "Impresionant"],
            benefitsEn: ["Very unique", "Physical challenge", "New sensations", "Impressive"],
            tips: ["Necesita experienta", "Incalzire prealabila", "Nu fortati"],
            tipsEn: ["Requires experience", "Prior warm-up", "Don't force it"],
            variations: ["Simplificata", "Cu sprijin", "Varianta pe lateral"],
            variationsEn: ["Simplified", "With support", "Side variant"]
        ),
        Position(
            id: "the-cross", name: "Crucea", nameEn: "The Cross",
            category: .intimate, difficulty: .intermediate, intimacy: 4,
            image: "the-cross",
            description: "Corpurile formand o cruce, cu penetrare laterala intima si relaxanta.",
            descriptionEn: "Bodies forming a cross, with intimate and relaxing lateral penetration.",
            benefits: ["Relaxant", "Intim", "Unghi diferit", "Perfect pentru prelungire"],
            benefitsEn: ["Relaxing", "Intimate", "Different angle", "Perfect for extended sessions"],
            tips: ["Perne pentru confort", "Miscari lente", "Gasiti unghiul ideal"],
            tipsEn: ["Pillows for comfort", "Slow movements", "Find the ideal angle"],
            variations: ["Cu picioarele ridicate", "Mai apropiati", "Cu bratele intinse"],
            variationsEn: ["With raised legs", "Closer together", "With arms extended"]
        ),
        Position(
            id: "the-suspended-congress", name: "Congresul Suspendat", nameEn: "Suspended Congress",
            category: .adventurous, difficulty: .expert, intimacy: 4,
            image: "the-suspended-congress",
            description: "Partenerul sustine complet partenera in aer, maxima incredere.",
            descriptionEn: "Partner fully supports the other in the air, maximum trust.",
            benefits: ["Incredere maxima", "Intensitate extrema", "Romantic", "Provocare fizica"],
            benefitsEn: ["Maximum trust", "Extreme intensity", "Romantic", "Physical challenge"],
            tips: ["Necesita forta fizica", "Incepeti langa perete", "Siguranta mai intai"],
            tipsEn: ["Requires physical strength", "Start near a wall", "Safety first"],
            variations: ["Cu sprijin pe perete", "Partial suspendat", "Cu sprijin pe mobila"],
            variationsEn: ["With wall support", "Partially suspended", "With furniture support"]
        ),
        Position(
            id: "the-side-saddle", name: "Sa laterala", nameEn: "Side Saddle",
            category: .intimate, difficulty: .intermediate, intimacy: 4,
            image: "the-side-saddle",
            description: "Partenera asezata lateral pe partener ca pe o sa laterala.",
            descriptionEn: "Partner seated sideways on partner like a side saddle.",
            benefits: ["Unghi unic", "Control pentru partenera", "Stimulare diferita", "Intim"],
            benefitsEn: ["Unique angle", "Control for partner", "Different stimulation", "Intimate"],
            tips: ["Gasiti echilibrul", "Sprijiniti-va pe maini", "Experimentati cu unghiul"],
            tipsEn: ["Find balance", "Support on hands", "Experiment with angle"],
            variations: ["Mai aplecat", "Cu sprijin pe spate", "Cu picioarele intinse"],
            variationsEn: ["More angled", "With back support", "With extended legs"]
        ),
        Position(
            id: "the-om", name: "Om-ul", nameEn: "The Om",
            category: .intimate, difficulty: .advanced, intimacy: 5,
            image: "the-om",
            description: "Pozitie tantra cu ambii parteneri in lotus, imbratisati si conectati spiritual.",
            descriptionEn: "Tantra position with both partners in lotus, embracing and spiritually connected.",
            benefits: ["Conexiune spirituala", "Intimitate maxima", "Respiratie sincronizata", "Meditativ"],
            benefitsEn: ["Spiritual connection", "Maximum intimacy", "Synchronized breathing", "Meditative"],
            tips: ["Practicati respiratia", "Mentineti contactul vizual", "Ritm foarte lent"],
            tipsEn: ["Practice breathing", "Maintain eye contact", "Very slow rhythm"],
            variations: ["Cu picioarele intinse", "Cu meditatia inainte", "Cu muzica ambientala"],
            variationsEn: ["With extended legs", "With meditation before", "With ambient music"]
        ),
        Position(
            id: "the-speed-bump", name: "Denivelarea", nameEn: "The Speed Bump",
            category: .passionate, difficulty: .beginner, intimacy: 3,
            image: "the-speed-bump",
            description: "Partenera intinsa pe burta cu o perna sub solduri pentru unghi perfect.",
            descriptionEn: "Partner lying face down with a pillow under hips for perfect angle.",
            benefits: ["Foarte usor", "Penetrare profunda", "Confortabil", "Stimulare G-spot"],
            benefitsEn: ["Very easy", "Deep penetration", "Comfortable", "G-spot stimulation"],
            tips: ["Perna sub solduri", "Picioarele usor departate", "Miscari lente"],
            tipsEn: ["Pillow under hips", "Legs slightly apart", "Slow movements"],
            variations: ["Cu picioarele unite", "Cu doua perne", "Cu bratele pe spate"],
            variationsEn: ["With legs together", "With two pillows", "With arms on back"]
        ),
        Position(
            id: "the-crab", name: "Crabul", nameEn: "The Crab",
            category: .adventurous, difficulty: .advanced, intimacy: 3,
            image: "the-crab",
            description: "Ambii parteneri in pozitie de crab, fata in fata, sprijiniti pe maini si picioare.",
            descriptionEn: "Both partners in crab position, face to face, supported on hands and feet.",
            benefits: ["Provocare fizica", "Unghi unic", "Senzatii noi", "Distractiv"],
            benefitsEn: ["Physical challenge", "Unique angle", "New sensations", "Fun"],
            tips: ["Necesita forta in brate", "Suprafata moale", "Nu fortati pozitia"],
            tipsEn: ["Requires arm strength", "Soft surface", "Don't force the position"],
            variations: ["Cu un partener pe spate", "Simplificata", "Cu sprijin pe coate"],
            variationsEn: ["With one partner on back", "Simplified", "With elbow support"]
        ),
        Position(
            id: "the-row-boat", name: "Barca cu Vasle", nameEn: "The Row Boat",
            category: .intimate, difficulty: .intermediate, intimacy: 5,
            image: "the-row-boat",
            description: "Fata in fata cu picioarele impletite, miscati-va inainte si inapoi ca intr-o barca.",
            descriptionEn: "Face to face with intertwined legs, move back and forth like in a boat.",
            benefits: ["Foarte intim", "Contact vizual constant", "Ritm sincronizat", "Romantic"],
            benefitsEn: ["Very intimate", "Constant eye contact", "Synchronized rhythm", "Romantic"],
            tips: ["Tineti-va de maini", "Miscari de legananare", "Sincronizati ritmul"],
            tipsEn: ["Hold hands", "Rocking movements", "Synchronize rhythm"],
            variations: ["Cu imbratisare", "Cu bratele libere", "Mai apropiati sau mai departati"],
            variationsEn: ["With embrace", "With free arms", "Closer or further apart"]
        ),
        Position(
            id: "the-gallery", name: "Galeria", nameEn: "The Gallery",
            category: .passionate, difficulty: .intermediate, intimacy: 3,
            image: "the-gallery",
            description: "Din spate cu partenera sprijinita de perete, vedere impresionanta.",
            descriptionEn: "From behind with partner leaning against wall, impressive view.",
            benefits: ["Spontan", "Intensitate mare", "Nu necesita pat", "Dominanta"],
            benefitsEn: ["Spontaneous", "High intensity", "No bed needed", "Dominant"],
            tips: ["Perete stabil", "Ajustati inaltimea", "Comunicati ritmul"],
            tipsEn: ["Stable wall", "Adjust height", "Communicate rhythm"],
            variations: ["Cu mainile pe perete", "Cu un picior ridicat", "Cu spatele la perete"],
            variationsEn: ["With hands on wall", "With one leg raised", "With back to wall"]
        ),
        Position(
            id: "the-seashell", name: "Scoica", nameEn: "The Seashell",
            category: .intimate, difficulty: .advanced, intimacy: 4,
            image: "the-seashell",
            description: "Partenera cu genunchii la piept, ca o scoica, pentru penetrare foarte profunda.",
            descriptionEn: "Partner with knees to chest, like a seashell, for very deep penetration.",
            benefits: ["Penetrare foarte profunda", "Stimulare G-spot", "Compacta", "Intima"],
            benefitsEn: ["Very deep penetration", "G-spot stimulation", "Compact", "Intimate"],
            tips: ["Flexibilitate necesara", "Incepeti incet", "Comunicati adancimea"],
            tipsEn: ["Flexibility required", "Start slowly", "Communicate depth"],
            variations: ["Cu un genunchi", "Cu picioarele pe umeri", "Varianta laterala"],
            variationsEn: ["With one knee", "With legs on shoulders", "Side variant"]
        ),
        Position(
            id: "the-stairway", name: "Scara", nameEn: "The Stairway",
            category: .adventurous, difficulty: .advanced, intimacy: 3,
            image: "the-stairway",
            description: "Pe scari, folosind treptele pentru a crea unghiuri diferite.",
            descriptionEn: "On stairs, using the steps to create different angles.",
            benefits: ["Unghiuri variate", "Spontan", "Foloseste mediul", "Senzatii noi"],
            benefitsEn: ["Various angles", "Spontaneous", "Uses environment", "New sensations"],
            tips: ["Atentie la siguranta", "Folositi covoras", "Experimentati cu treptele"],
            tipsEn: ["Be careful about safety", "Use a rug", "Experiment with steps"],
            variations: ["Asezat pe o treapta", "In picioare", "Cu partenera pe treapta superioara"],
            variationsEn: ["Seated on a step", "Standing", "With partner on upper step"]
        ),
        Position(
            id: "the-lap-dance", name: "Dansul din Poala", nameEn: "Lap Dance",
            category: .passionate, difficulty: .beginner, intimacy: 4,
            image: "the-lap-dance",
            description: "Partenera danseaza senzual in poala partenerului asezat.",
            descriptionEn: "Partner dances sensually in the lap of the seated partner.",
            benefits: ["Foarte seducator", "Preludiu excelent", "Spontan", "Distractiv"],
            benefitsEn: ["Very seductive", "Excellent foreplay", "Spontaneous", "Fun"],
            tips: ["Muzica potrivita", "Miscari lente", "Contact vizual"],
            tipsEn: ["Right music", "Slow movements", "Eye contact"],
            variations: ["Cu muzica", "Cu lumina slaba", "Cu contact minim"],
            variationsEn: ["With music", "With dim light", "With minimal contact"]
        ),
        Position(
            id: "the-tabletop", name: "Masa", nameEn: "The Tabletop",
            category: .passionate, difficulty: .intermediate, intimacy: 3,
            image: "the-tabletop",
            description: "Partenera asezata pe masa sau blat cu partenerul in picioare.",
            descriptionEn: "Partner seated on table or counter with other partner standing.",
            benefits: ["Spontan", "Unghi perfect", "Stimulare intensa", "Nu necesita pat"],
            benefitsEn: ["Spontaneous", "Perfect angle", "Intense stimulation", "No bed needed"],
            tips: ["Suprafata stabila", "Inaltime potrivita", "Atentie la obiecte"],
            tipsEn: ["Stable surface", "Right height", "Watch for objects"],
            variations: ["Pe masa", "Pe blatul de bucatarie", "Pe birou"],
            variationsEn: ["On table", "On kitchen counter", "On desk"]
        ),
        Position(
            id: "the-toad", name: "Broasca", nameEn: "The Toad",
            category: .passionate, difficulty: .intermediate, intimacy: 3,
            image: "the-toad",
            description: "Partenera pe vine cu partenera aplecata inainte, pozitie de broasca.",
            descriptionEn: "Partner squatting with forward lean, frog-like position.",
            benefits: ["Penetrare profunda", "Control pentru partenera", "Stimulare intensa", "Unghi unic"],
            benefitsEn: ["Deep penetration", "Control for partner", "Intense stimulation", "Unique angle"],
            tips: ["Necesita rezistenta in picioare", "Sprijiniti-va pe maini", "Pauze daca e nevoie"],
            tipsEn: ["Requires leg endurance", "Support on hands", "Breaks if needed"],
            variations: ["Cu sprijin", "Pe jumatate", "Cu perna de sprijin"],
            variationsEn: ["With support", "Halfway", "With support pillow"]
        ),
        Position(
            id: "the-throne", name: "Tronul", nameEn: "The Throne",
            category: .intimate, difficulty: .intermediate, intimacy: 4,
            image: "the-throne",
            description: "Partenerul asezat ca pe un tron cu partenera in poala, fata in fata.",
            descriptionEn: "Partner seated as on a throne with other partner in lap, face to face.",
            benefits: ["Foarte intim", "Control partajat", "Sarutari usoare", "Romantic"],
            benefitsEn: ["Very intimate", "Shared control", "Easy kissing", "Romantic"],
            tips: ["Scaun confortabil", "Imbratisati-va", "Ritm lent"],
            tipsEn: ["Comfortable chair", "Embrace each other", "Slow rhythm"],
            variations: ["Pe fotoliu", "Pe canapea", "Pe marginea patului"],
            variationsEn: ["On armchair", "On couch", "On edge of bed"]
        ),
        Position(
            id: "the-pinwheel", name: "Moriscuta", nameEn: "The Pinwheel",
            category: .adventurous, difficulty: .advanced, intimacy: 3,
            image: "the-pinwheel",
            description: "Corpurile rotite intr-un unghi ca o morisca, pozitie unica.",
            descriptionEn: "Bodies rotated at an angle like a pinwheel, unique position.",
            benefits: ["Foarte unic", "Senzatii noi", "Stimulare diferita", "Creativitate"],
            benefitsEn: ["Very unique", "New sensations", "Different stimulation", "Creativity"],
            tips: ["Experimentati cu unghiul", "Comunicati confortul", "Miscari lente"],
            tipsEn: ["Experiment with angle", "Communicate comfort", "Slow movements"],
            variations: ["Cu unghi mai mic", "Cu sprijin pe perne", "Varianta simplificata"],
            variationsEn: ["With smaller angle", "With pillow support", "Simplified variant"]
        ),
        Position(
            id: "the-sultry-saddle", name: "Sa Senzuala", nameEn: "Sultry Saddle",
            category: .passionate, difficulty: .intermediate, intimacy: 4,
            image: "the-sultry-saddle",
            description: "Partenera calare pe partener cu miscare de senzualitate maxima.",
            descriptionEn: "Partner riding with maximum sensuality movement.",
            benefits: ["Control pentru partenera", "Stimulare intensa", "Senzual", "Ritm variat"],
            benefitsEn: ["Control for partner", "Intense stimulation", "Sensual", "Varied rhythm"],
            tips: ["Miscari circulare", "Variati ritmul", "Contact vizual"],
            tipsEn: ["Circular movements", "Vary the rhythm", "Eye contact"],
            variations: ["Cu aplecare inainte", "Cu aplecare inapoi", "Cu miscari laterale"],
            variationsEn: ["With forward lean", "With backward lean", "With side movements"]
        ),
        Position(
            id: "the-folding-chair", name: "Scaunul Pliabil", nameEn: "Folding Chair",
            category: .adventurous, difficulty: .advanced, intimacy: 3,
            image: "the-folding-chair",
            description: "Partenera pliata cu genunchii la piept si partenerul in genunchi.",
            descriptionEn: "Partner folded with knees to chest and other partner kneeling.",
            benefits: ["Penetrare profunda", "Unghi intens", "Compacta", "Stimulare G-spot"],
            benefitsEn: ["Deep penetration", "Intense angle", "Compact", "G-spot stimulation"],
            tips: ["Flexibilitate necesara", "Comunicati confortul", "Incepeti incet"],
            tipsEn: ["Flexibility required", "Communicate comfort", "Start slowly"],
            variations: ["Cu un picior intins", "Cu sprijin lateral", "Varianta deschisa"],
            variationsEn: ["With one leg extended", "With lateral support", "Open variant"]
        ),
        Position(
            id: "the-column", name: "Coloana", nameEn: "The Column",
            category: .adventurous, difficulty: .advanced, intimacy: 3,
            image: "the-column",
            description: "Ambii parteneri in picioare, una in fata celuilalt, ca o coloana.",
            descriptionEn: "Both partners standing, one in front of the other, like a column.",
            benefits: ["Spontan", "In picioare", "Intensitate", "Nu necesita pat"],
            benefitsEn: ["Spontaneous", "Standing", "Intensity", "No bed needed"],
            tips: ["Gasiti inaltimea potrivita", "Sprijiniti-va de ceva", "Stabilitate"],
            tipsEn: ["Find the right height", "Lean on something", "Stability"],
            variations: ["Langa perete", "Langa usa", "Cu un picior ridicat"],
            variationsEn: ["Near wall", "Near door", "With one leg raised"]
        ),
        Position(
            id: "the-proposal", name: "Cererea", nameEn: "The Proposal",
            category: .romantic, difficulty: .intermediate, intimacy: 4,
            image: "the-proposal",
            description: "Partenerul in genunchi in fata partenerei, pozitie de adoratie.",
            descriptionEn: "Partner kneeling before the other, a position of adoration.",
            benefits: ["Romantic", "Adoratie", "Stimulare orala", "Emotional"],
            benefitsEn: ["Romantic", "Adoration", "Oral stimulation", "Emotional"],
            tips: ["Perna sub genunchi", "Contact vizual", "Ritm lent"],
            tipsEn: ["Pillow under knees", "Eye contact", "Slow rhythm"],
            variations: ["Cu partenera pe marginea patului", "Pe scaun", "In picioare"],
            variationsEn: ["With partner on edge of bed", "On chair", "Standing"]
        ),
        Position(
            id: "the-lusty-leg", name: "Piciorul Senzual", nameEn: "The Lusty Leg",
            category: .passionate, difficulty: .intermediate, intimacy: 4,
            image: "the-lusty-leg",
            description: "Partenera cu un picior ridicat pe umarul partenerului, in picioare.",
            descriptionEn: "Partner with one leg raised on the other's shoulder, standing.",
            benefits: ["Penetrare profunda", "Flexibilitate", "Spontan", "Senzual"],
            benefitsEn: ["Deep penetration", "Flexibility", "Spontaneous", "Sensual"],
            tips: ["Incalziti-va muschii", "Sprijiniti-va de perete", "Flexibilitate necesara"],
            tipsEn: ["Warm up muscles", "Lean on wall", "Flexibility required"],
            variations: ["Cu sprijin pe perete", "Cu piciorul pe brat", "Cu piciorul pe sold"],
            variationsEn: ["With wall support", "With leg on arm", "With leg on hip"]
        ),
        Position(
            id: "the-sofa-brace", name: "Sprijinul pe Canapea", nameEn: "Sofa Brace",
            category: .passionate, difficulty: .beginner, intimacy: 3,
            image: "the-sofa-brace",
            description: "Partenera aplecata peste brat canapelei cu partenerul din spate.",
            descriptionEn: "Partner bent over the sofa arm with the other from behind.",
            benefits: ["Foarte spontan", "Confortabil", "Intensitate", "Acces liber"],
            benefitsEn: ["Very spontaneous", "Comfortable", "Intensity", "Free access"],
            tips: ["Inaltimea potrivita a canapelei", "Perna pentru confort", "Comunicati ritmul"],
            tipsEn: ["Right sofa height", "Pillow for comfort", "Communicate rhythm"],
            variations: ["Peste bratul canapelei", "Peste speteaza", "Pe canapea in genunchi"],
            variationsEn: ["Over sofa arm", "Over backrest", "Kneeling on sofa"]
        ),
        Position(
            id: "the-double-decker", name: "Etajera Dubla", nameEn: "Double Decker",
            category: .intimate, difficulty: .intermediate, intimacy: 5,
            image: "the-double-decker",
            description: "Ambii parteneri intinsi, unul peste altul, cu contact corporal maxim.",
            descriptionEn: "Both partners lying, one on top of the other, with maximum body contact.",
            benefits: ["Contact maxim", "Foarte intim", "Relaxant", "Sarutari usor de oferit"],
            benefitsEn: ["Maximum contact", "Very intimate", "Relaxing", "Easy to kiss"],
            tips: ["Nu puneti prea multa greutate", "Miscari mici si lente", "Imbratisati-va"],
            tipsEn: ["Don't put too much weight", "Small and slow movements", "Embrace each other"],
            variations: ["Cu bratele impletite", "Cu picioarele impletite", "Cu perna sub solduri"],
            variationsEn: ["With arms intertwined", "With legs intertwined", "With pillow under hips"]
        ),
        Position(
            id: "the-champagne-room", name: "Camera Sampaniei", nameEn: "Champagne Room",
            category: .adventurous, difficulty: .advanced, intimacy: 4,
            image: "the-champagne-room",
            description: "Pozitie luxoasa pe o suprafata eleganta, celebrand momentul.",
            descriptionEn: "Luxurious position on an elegant surface, celebrating the moment.",
            benefits: ["Elegant", "Festiv", "Senzatii noi", "Special"],
            benefitsEn: ["Elegant", "Festive", "New sensations", "Special"],
            tips: ["Creati o atmosfera speciala", "Sampanie optionala", "Lumina de lumanari"],
            tipsEn: ["Create a special atmosphere", "Champagne optional", "Candlelight"],
            variations: ["Pe covorul pufos", "Pe cada", "Pe balcon"],
            variationsEn: ["On fluffy carpet", "On bathtub", "On balcony"]
        ),
        Position(
            id: "the-bodyguard", name: "Garda de Corp", nameEn: "The Bodyguard",
            category: .romantic, difficulty: .beginner, intimacy: 4,
            image: "the-bodyguard",
            description: "Partenerul in spatele partenerei, imbratisand-o protector, ambii in picioare.",
            descriptionEn: "Partner behind the other, embracing protectively, both standing.",
            benefits: ["Protector", "Intim", "Spontan", "Romantic"],
            benefitsEn: ["Protective", "Intimate", "Spontaneous", "Romantic"],
            tips: ["Imbratisati-va strans", "Soptiti la ureche", "Miscari lente"],
            tipsEn: ["Embrace tightly", "Whisper in ear", "Slow movements"],
            variations: ["In fata oglinzii", "Sub dus", "Langa geam"],
            variationsEn: ["In front of mirror", "In shower", "By the window"]
        ),
        Position(
            id: "the-turtle", name: "Testoasa", nameEn: "The Turtle",
            category: .intimate, difficulty: .beginner, intimacy: 4,
            image: "the-turtle",
            description: "Partenera ghemuita cu partenerul deasupra, protectiv si intim.",
            descriptionEn: "Partner curled up with the other on top, protective and intimate.",
            benefits: ["Foarte intim", "Protector", "Confortabil", "Penetrare profunda"],
            benefitsEn: ["Very intimate", "Protective", "Comfortable", "Deep penetration"],
            tips: ["Perne pentru confort", "Miscari lente", "Comunicati presiunea"],
            tipsEn: ["Pillows for comfort", "Slow movements", "Communicate pressure"],
            variations: ["Cu perna sub genunchi", "Mai deschisa", "Cu bratele intinse"],
            variationsEn: ["With pillow under knees", "More open", "With arms extended"]
        ),
    ]
}
